# Generated by Django 4.0.6 on 2022-07-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_name', models.CharField(error_messages={'unique': 'A product with that name already exists.'}, max_length=50, unique=True, verbose_name='prd_name')),
                ('prd_created', models.DateTimeField(auto_now_add=True)),
                ('prd_warehause', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['prd_name'],
            },
        ),
        migrations.CreateModel(
            name='Warehauses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whs_name', models.CharField(error_messages={'unique': 'A warehause with that name already exists.'}, max_length=50, unique=True, verbose_name='whs_name')),
                ('whs_address', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['whs_name'],
            },
        ),
    ]
