# Generated by Django 4.1.5 on 2023-01-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.BooleanField(default=False)),
                ('kilometers', models.TextField(max_length=32)),
                ('horse_power', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
    ]
